---

- name: tmux_conf_reload
  shell: tmux source-file ~/.tmux.conf

# # Load the configuration file in tmux
# tmux source-file ~/.tmux.conf

# # Install the plugins 
# ~/.tmux/plugins/tpm/bin/install_plugins

# # Update the plugins
# ~/.tmux/plugins/tpm/bin/update_plugins all