---
- hosts: localhost
  connection: local
  tasks:
    - homebrew: name={{ item }} state=present update_homebrew=yes
      with_items:
      - git
      - vim
      - zsh

    - homebrew_cask: name={{ item }} state=present
      with_items:
      - google-chrome

