---

- homebrew: name=zsh state=present update_homebrew=yes

- name: Get current shell
  shell: echo $SHELL
  register: shell_used
  changed_when: False

- block:
  - name: Get username
    shell: whoami
    register: current_user
    changed_when: False

  - lineinfile: dest=/etc/shells line={{ shell_path }}
    become: true

  - name: Change the default shell to zsh for current user
    user: name={{ current_user.stdout }} shell={{ shell_path }}
    become: true
  when: shell_used.stdout != shell_path

- name: zsh aliases file
  copy: src=aliases dest=~/.aliases

- name: zsh config file
  copy: src=zshrc dest=~/.zshrc

- name: Install oh my zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh

