---

- homebrew: name={{ item }} state=present update_homebrew=yes
  with_items:
    - git
    - hub

- name: Git ignore file
  copy: src=gitignore dest=~/.gitignore

- name: Git config file
  template: src=gitconfig dest=~/.gitconfig

