"
" Load plugins
"

" Allow vim to break compatibility with vi
set nocompatible        " This must be first, because it changes other options
filetype off            " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'altercation/vim-colors-solarized'

Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'

Plugin 'scrooloose/syntastic'

Plugin 'mattn/emmet-vim'

Plugin 'bronson/vim-trailing-whitespace'

" All of your Plugins must be added before the following line
call vundle#end()           " required

set autoindent
filetype plugin indent on   " Reactivate file type detection


"
" User settings
"

set encoding=utf-8              " The encoding displayed.
syntax enable                   " Syntax highlighting
set background=light            " Change color scheme variation
colorscheme solarized           " Change vim color scheme

let mapleader="\<Space>"        " Leader key is comma

set clipboard=unnamed           " Use system clipboard

set showcmd                     " Show command down at the bottom
set showmode                    " Show current mode down at the bottom

set relativenumber              " Display relative line numbers
set number                      " Display line numbers

set tabstop=4                   " Number of visual spaces per TAB
set softtabstop=4               " Number of spaces in tab when editing
set expandtab                   " Tabs are spaces
set shiftwidth=4                " Number of columns for text indentation

set showmatch                   " Highlight matching [{()}]

set incsearch                   " Activate incremental search
set hlsearch                    " Activate search hilighting

set history=3000                " Extends the remembered commands


"
" Leader shortcuts
"

map <Leader>w :w<CR>                " Save file
map <Leader>x :x<CR>                " Save file and exit

"
" Plugin settings
"

map <Leader>o :CtrlP<CR>            " Open CtrlP
map <Leader>n :NERDTreeToggle<CR>   " Toggle NERDTree filesystem tree split
map <Leader>wf :FixWhitespace<CR>   " Remove trailling whitespace

