"
" Load plugins
"

" Allow vim to break compatibility with vi
set nocompatible        " This must be first, because it changes other options
filetype off            " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'

Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/syntastic'
Plug 'kien/ctrlp.vim', { 'on': 'CtrlP' }

Plug 'bronson/vim-trailing-whitespace', { 'on': 'FixWhitespace' }

Plug 'christoomey/vim-tmux-navigator'

Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown'] }

" Initialize plugin system
call plug#end()

set autoindent
filetype plugin indent on   " Reactivate file type detection


"
" User settings
"

set encoding=utf-8              " The encoding displayed.
syntax enable                   " Syntax highlighting
set background=dark            " Change color scheme variation

" Change vim color scheme
silent! colorscheme solarized

set backspace=indent,eol,start  " Make backspace work as expected
let mapleader="\<Space>"        " Leader key is comma

set clipboard=unnamed           " Use system clipboard

set showcmd                     " Show command down at the bottom
set showmode                    " Show current mode down at the bottom

set relativenumber              " Display relative line numbers
set number                      " Display line numbers

set tabstop=4                   " Number of visual spaces per TAB
set softtabstop=4               " Number of spaces in tab when editing
set expandtab                   " Tabs are spaces
set shiftwidth=4                " Number of columns for text indentation

set showmatch                   " Highlight matching [{()}]

set incsearch                   " Activate incremental search
set hlsearch                    " Activate search hilighting

set history=3000                " Extends the remembered commands

set swapfile
set dir=~/tmp

"
" File indentation
"
au BufNewFile,BufRead *.yaml.*      set filetype=yaml
au BufNewFile,BufRead *.yaml        set filetype=yaml
au BufNewFile,BufRead *.yml.*       set filetype=yaml
au BufNewFile,BufRead *.yml         set filetype=yaml
autocmd Filetype yaml setlocal ts=2 sts=2 sw=2

autocmd Filetype javascript setlocal ts=2 sts=2 sw=2

"
" Shortcuts
"

inoremap <special> jk <ESC>


"
" Plugin settings
"

let NERDTreeIgnore = ['\.pyc$']


"
" Leader shortcuts
"

" Save file
nnoremap <Leader>w :w<CR>

" Save file and exit
nnoremap <Leader>x :x<CR>

"
" Plugin settings
"

" Open CtrlP
nnoremap <Leader>o :CtrlP<CR>

" Toggle NERDTree filesystem tree split
nnoremap <Leader>n :NERDTreeToggle<CR>

" Remove trailling whitespace
nnoremap <Leader>fw :FixWhitespace<CR>

" Ctrlp
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(\.(swp|ico|git|svn))$'

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'npm run lint --'

