- homebrew_cask: name={{ item }} state=present
  with_items:
    - flux

    - iterm2
    - visual-studio-code
    - jetbrains-toolbox

    - google-chrome
    - firefox

    - virtualbox
    - docker

    - sketch
    - spotify

    - whatsapp
    - skype
    - slack

- homebrew_cask: name={{ item }} state=absent
  with_items:
    - caffeine
    - bettertouchtool
    - vagrant
    - evernote


- name: Ensure MAS is installed.
  homebrew: name=mas state=present

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  changed_when: false

- name: Ensure configured MAS apps are installed
  command: mas install "{{ item.id|default(item) }}"
  with_items:
    - { id: 937984704, name: "Amphetamine (4.0.3)" }
    - { id: 441258766, name: "Magnet (2.4)" }
    - { id: 497799835, name: "Xcode (10.0)" }
  when: (item.id | default(item) | string) not in mas_list.stdout
