---

- name: "Menu bar: show battery percentage"
  osx_defaults: domain=com.apple.menuextra.battery key=ShowPercent type=string value="YES"

- name: "Trackpad: enable tap to click for this user"
  osx_defaults: domain=com.apple.AppleMultitouchTrackpad key=Clicking type=int value=1

- name: "Trackpad: three finger drag"
  osx_defaults: domain=com.apple.AppleMultitouchTrackpad key=TrackpadThreeFingerDrag type=bool value=true

- name: "Require password after sleep or screen saver"
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1

- name: "Request password immediately after sleep or screen saver"
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=float value=0

- name: "Finder: show path bar"
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true

- name: "Finder: when performing a search, search the current folder by default"
  osx_defaults: domain=com.apple.finder key=FXDefaultSearchScope type=string value="SCcf"

- name: "Dock: turn on autohide"
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true

- name: "Dock: set the icon size of Dock items to 36 pixels"
  osx_defaults: domain=com.apple.dock key=tilesize type=float value=36

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

- name: "Top left screen corner → Put display to sleep"
  osx_defaults: domain=com.apple.dock key=wvous-tl-corner type=int value=10

- name: "Top left screen corner no modifier"
  osx_defaults: domain=com.apple.dock key=wvous-tl-modifier type=int value=0

- name: "Don’t display the annoying prompt when quitting iTerm"
  osx_defaults: domain=com.googlecode.iterm2 key=PromptOnQuit type=bool value=false
