---

- homebrew: name=vim state=present update_homebrew=yes

- name: Creates directory
  file: path=~/.vim/autoload state=directory

- name: Creates vim swap file directory
  file: path=~/tmp state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Vimrc file
  copy: src=vimrc dest=~/.vimrc force=yes
  register: vimrc_loaded

- name: Install vim plugins
  shell: vim +PlugInstall +qall
  when: vimrc_loaded.changed

