---

- homebrew: name=vim state=present update_homebrew=yes

- name: Install vundle plugin manager
  git: repo=https://github.com/VundleVim/Vundle.vim.git
       dest=~/.vim/bundle/Vundle.vim

- name: Vimrc file
  copy: src=vimrc dest=~/.vimrc force=yes
  register: vimrc_loaded

- name: Install vim plugins
  shell: vim +PluginInstall +qall
  when: vimrc_loaded.changed

- name: Create ftplugin directory
  file: path=~/.vim/ftlplugin/ state=directory mode=0755

- name: Copy ftplugin files
  copy: src=ftplugin/{{ item }} dest=~/.vim/ftlplugin/{{ item }}force=yes
  with_items:
    - javascript.vim
    - yaml.vim